### ISSUE TITLE
Not working as expected in Xcode 12 beta 6

### ISSUE THREAD

**Issue by westerlund** [NicholasBellucci/SociableWeaver#38]
Hi!

We're using SociableWeaver in our project and it has been great, however when building in Xcode 12 our project fails and when running the SociableWeaver tests, all but three tests fails.

Version: v0.1.7
Xcode: 12.0 beta 6 (12A8189n)

**Comment by NicholasBellucci** [comment]
Thanks for bringing this to my attention. I haven't upgraded to Big Sur yet so i haven't been able to test everything on Xcode 12. Any chance you are able to see why the tests might be failing?

**Comment by westerlund** [comment]
> Thanks for bringing this to my attention. I haven't upgraded to Big Sur yet so i haven't been able to test everything on Xcode 12. Any chance you are able to see why the tests might be failing?

Sure, I've attached the `xcresult` which you can open in older Xcodes as well!
You don't need Big Sur to run Xcode 12, I'm on Catalina 10.15.6 and it works just fine here.

[Test-SociableWeaver-Package-2020.09.09_15-07-20-+0200.xcresult.zip](https://github.com/NicholasBellucci/SociableWeaver/files/5195336/Test-SociableWeaver-Package-2020.09.09_15-07-20-%2B0200.xcresult.zip)

**Comment by NicholasBellucci** [comment]
Oh nice. Well in that case let me get it downloaded and I can see what sort of fixes are needed.

**Comment by NicholasBellucci** [comment]
Should be resolved as of version 0.1.8. Turns out there is more function builder support as of beta 6. The `.individual` hack should no longer be needed for `Weave` and `Object`. Let me know if you have any more issues. I will be updating the README to reflect these new changes.
