### ISSUE TITLE
How to pass object array to Weave init in OperationBuilder parameter

### ISSUE THREAD

**Issue by bududomasidet** [NicholasBellucci/SociableWeaver#42]
<img width="789" alt="Screenshot 2020-11-07 at 16 30 52" src="https://user-images.githubusercontent.com/15055998/98442641-cc913e80-2116-11eb-9dc5-81f93cede519.png">

Hey there!
Could you please tell me if its possible to build Weave query like this. I didn't find any approach here. Not so familiar with FunctionBuilders

**Comment by NicholasBellucci** [comment]
So currently this wouldn't be supported as the function builder is expecting a type that conforms to ObjectWeavable but this poses an interesting situation. In theory I might be able to build out a custom solution for this issue. Let me look into this some today and see what I can come up with.

**Comment by NicholasBellucci** [comment]
Could you help me out a little and give me an idea of your end goal. Maybe a quick mock of the desired query.

**Comment by bududomasidet** [comment]
Hey Nicholas!
Thank you for the answer :) 
The final query I want to request can be represented like this:
`
{
  ort_first: visitor(site: ort) {
    tv {
      onAirShowNext(channel: ORT_1) {
        ...showFragment
      }
    }
  }
  ort_second: visitor(site: ORT) {
    tv {
      onAirShowNext(channel: ORT_2) {
        ...showFragment
      }
    }
  }
  ....
}

fragment imageUriFragment on Image {
  src {
    absoluteUri
  }
}

fragment showFragment on Show {
  name
  startsAt
  endsAt
  hosts {
    name
    defaultImage {
      alexa340: legacyImage(recipe: "alexa340") {
        ...imageUriFragment
      }
    }
  }
  guests {
    name
  }
}
`

I tried to write ForEach statement with OperationBuilder, but failed to do it :(

**Comment by NicholasBellucci** [comment]
Ok so yesterday I created a ForEachWeavable which can be found on a new branch here: https://github.com/NicholasBellucci/SociableWeaver/tree/feature/foreach-weavable. If you would like to check this branch out and then refer to a new test that I added this might be a start to solving this use case. https://github.com/NicholasBellucci/SociableWeaver/blob/66139d297997ab326638e4643091e795795e2b7d/Tests/SociableWeaverTests/SociableWeaverBuilderTests.swift#L238

Please feel free to provide any sort of feedback and we can converse on how to make this solution work best.

**Comment by bududomasidet** [comment]
Wow! Seems like everything works fine! 
Will you add `public init` for ForEachWeavable?
Thank you @NicholasBellucci 👍  
I don't have an idea how can it be improved for now. I will take a look after finishing project. 

But I really enjoy your declarative stuff on GraphQL requests 💯

**Comment by NicholasBellucci** [comment]
Version 0.1.11 now supports ForEachWeavable. I will document later this evening. Glad everything worked well. Going to close the issue but if anything comes up feel free to create a new one!
