### ISSUE TITLE
Pseudo graphql

### ISSUE THREAD

**Issue by vinamelody** [NicholasBellucci/SociableWeaver#44]
Hi, I'm given a subscription graphql url like this by the backend:
```
curl --insecure -X POST https://someserver.io/app/v1/maintenance/subscribe

returns:
{
   "data":{
      "maintenance":{
         "message":"Maintenance message here",
         "isMaintenance":false
      }
   }
}

```
After which, I understand that it's a pseudo graphql implemented on their side.

Is it possible to do this using SociableWeaver?
I mean, just by giving the url without knowing the actual graphql endpoint and the query. I have not implemented any networking at all :)

Thank you in advanced!

**Comment by NicholasBellucci** [comment]
SociableWeaver only handles creating the GraphQL queries. It doesn't actually handle any networking requests or responses. Hopefully this answers your question. Let me know if I misinterpreted the issue.

**Comment by vinamelody** [comment]
Hi @NicholasBellucci ah I see, apologize i also misunderstood the library 😂
