### ISSUE TITLE
mutation with upload variable

### ISSUE THREAD

**Issue by quentinfasquel** [NicholasBellucci/SociableWeaver#47]
I wonder how to use Sociable Weaver to describe such information, I don't think this is currently possible but I would like to make sure, for now the only case I can't use your library is for my mutation that requires uploading a file.

```
mutation MyOperation($preview: Upload, $file: Upload) {
    ...
}
```

Thanks.

**Comment by NicholasBellucci** [comment]
Hey sorry I just noticed this issue. I have been pretty busy at work and don't have as much time to look at stuff. Are you still experiencing this issue? Maybe I can throw something together.
