### ISSUE TITLE
Build issues with Xcode 14

### ISSUE THREAD

**Issue by kunal30xi** [NicholasBellucci/SociableWeaver#48]
Attempts to generate an xcframework via Carthage on Xcode 14 fail. 

System information:
Monterey 12.6 on Apple M1 Pro
Xcode 14.0.1
Carthage 0.38.0
SociableWeaver v 0.1.12

Relevant information from the Carthage logs

```
Users/username/Git/App/Carthage/Checkouts/SociableWeaver/Sources/SociableWeaver/FunctionBuilders/OperationBuilder.swift:19:44: error: cannot find type 'ForEachWeavable' in scope
            } else if let forEach = $0 as? ForEachWeavable {
                                           ^~~~~~~~~~~~~~~
/Users/username/Git/App/Carthage/Checkouts/SociableWeaver/Sources/SociableWeaver/FunctionBuilders/OperationBuilder.swift:7:18: error: type of expression is ambiguous without more context
        children.forEach {
        ~~~~~~~~~^~~~~~~~~

** ARCHIVE FAILED **

```

**Comment by NicholasBellucci** [comment]
Hey @kunal30xi the Carthage support was a PR from someone contributing to the library. I think a change to the code has been made since then. You wouldn't happen to know if updates need to occur when this happens would you? I am not familiar with Carthage.
